 Ingredient.create(name: "Light rum")
 Ingredient.create(name: "Applejack")
 Ingredient.create(name: "Gin")
 Ingredient.create(name: "Dark rum")
 Ingredient.create(name: "Sweet vermouth")
 Ingredient.create(name: "Peach schnapps")
 Ingredient.create(name: "Vodka")
 Ingredient.create(name: "Tequila blanco")
 Ingredient.create(name: "Spiced rum")
 Ingredient.create(name: "Mint leaves")
 Ingredient.create(name: "Scotch")
 Ingredient.create(name: "Triple sec")
 Ingredient.create(name: "Southern Comfort")
 Ingredient.create(name: "Simple syrup")
 Ingredient.create(name: "Brandy")
 Ingredient.create(name: "Baileys")
 Ingredient.create(name: "Frangelico")
 Ingredient.create(name: "Kahlua")
 Ingredient.create(name: "Club soda")
 Ingredient.create(name: "Tonic Water")
 Ingredient.create(name: "Coca-Cola")
 Ingredient.create(name: "7Up")
 Ingredient.create(name: "Orange juice")
 Ingredient.create(name: "Angostura Bitters")
 Ingredient.create(name: "Orange bitters")
 Ingredient.create(name: "Lemon juice")
